# Generated by Django 4.2.2 on 2023-06-11 05:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0003_course_is_deleted_modules_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='has_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modules',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='group',
            field=models.CharField(default='PPT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('PPT', 'Ppt')], default='PPT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('owner', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='coursedetails',
            unique_together={('student', 'course')},
        ),
        migrations.CreateModel(
            name='ModulesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.course')),
            ],
            options={
                'unique_together': {('course', 'title')},
            },
        ),
    ]
