# Generated by Django 4.2.2 on 2023-06-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0004_course_created_on_coursedetails_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default=None, null=True)),
                ('url', models.CharField(default='', max_length=200)),
                ('type', models.CharField(choices=[('REPORT', 'Report'), ('PROGRAMMING', 'Programming'), ('BOTH', 'Both')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=90000, null=True)),
                ('test_cases', models.CharField(max_length=90000)),
                ('final_cases', models.CharField(max_length=90000)),
                ('compilation_score', models.IntegerField(default=10)),
                ('running_score', models.IntegerField(default=10)),
                ('test_cases_score', models.IntegerField(default=10)),
                ('final_cases_score', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_score', models.IntegerField(default=0)),
                ('compilation_score', models.IntegerField(default=10)),
                ('running_score', models.IntegerField(default=10)),
                ('test_cases_score', models.IntegerField(default=10)),
                ('final_cases_score', models.IntegerField(default=10)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=90000, null=True)),
                ('late_submission', models.BooleanField(default=False)),
                ('plag', models.FloatField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.profile')),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(default='', max_length=200)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('PPT', 'Ppt')], max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='CourseDetails',
            new_name='CourseDetail',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, default='Welcome to this module', max_length=10000, null=True),
        ),
        migrations.RenameModel(
            old_name='ModulesGroup',
            new_name='ModuleGroup',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.course'),
        ),
        migrations.AddField(
            model_name='module',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.modulegroup'),
        ),
        migrations.AddField(
            model_name='assignmentremark',
            name='assignment_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='assignmentgroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.assignmentcode'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.assignmentgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('group', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentremark',
            unique_together={('assignment_submission', 'assignment')},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentgroup',
            unique_together={('course', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('group', 'title')},
        ),
    ]
