# Generated by Django 4.2.2 on 2023-06-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0005_assignment_assignmentcode_assignmentgroup_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentremark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_remark_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentremark',
            name='is_final_remark',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignmentremark',
            name='remark_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='useAuth.profile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assignmentremark',
            unique_together={('assignment_submission', 'assignment', 'remark_by')},
        ),
        migrations.CreateModel(
            name='NotificationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2500)),
                ('description', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.course')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useAuth.notificationdetail')),
            ],
        ),
    ]
