# Generated by Django 4.2.2 on 2023-06-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0007_alter_assignmentcode_table_alter_notification_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignmentcode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notificationdetail',
            table=None,
        ),
    ]
