# Generated by Django 4.2.2 on 2023-06-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0008_alter_assignmentcode_table_alter_notification_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='module',
            name='url',
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(default='', upload_to='assignment/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(default='', upload_to='modules/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='profile_pictures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='courses/'),
            preserve_default=False,
        ),
    ]
