# Generated by Django 4.2.2 on 2023-06-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0010_alter_assignment_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentremark',
            unique_together={('assignment_submission', 'assignment')},
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='url',
        ),
        migrations.AddField(
            model_name='assignmentremark',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='useAuth.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(default=None, upload_to='assignment_submissions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentremark',
            name='remark_by',
            field=models.CharField(max_length=50),
        ),
    ]
