# Generated by Django 4.2.2 on 2023-06-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0011_alter_assignmentremark_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcode',
            name='code',
            field=models.CharField(default='', max_length=90000, null=True),
        ),
        migrations.AddField(
            model_name='assignmentcode',
            name='user_code',
            field=models.CharField(default='', max_length=90000, null=True),
        ),
    ]
