# Generated by Django 4.2.2 on 2023-06-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0012_assignmentcode_code_assignmentcode_user_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='group',
        ),
    ]
