# Generated by Django 4.2.2 on 2023-06-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0014_delete_assignmentgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentcode',
            old_name='final_cases',
            new_name='imports',
        ),
        migrations.RemoveField(
            model_name='assignmentcode',
            name='test_cases',
        ),
    ]
