# Generated by Django 4.2.2 on 2023-06-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0015_rename_final_cases_assignmentcode_imports_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('course', 'title')},
        ),
    ]
