# Generated by Django 4.2.2 on 2023-06-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0017_rename_code_assignmentcode_solution_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('NOTHING', 'Nothing'), ('PROGRAMMING', 'Programming'), ('REPORT', 'Report'), ('BOTH', 'Both')], default='NOTHING', max_length=20),
        ),
    ]
