# Generated by Django 4.2.2 on 2023-06-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0019_alter_assignmentremark_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
