# Generated by Django 4.2.2 on 2023-06-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0022_rename_assignment_submission_assignmentremark_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentremark',
            name='code_remark',
            field=models.CharField(default='No Remark Provided', max_length=5000),
        ),
        migrations.AddField(
            model_name='assignmentremark',
            name='report_remark',
            field=models.CharField(default='No Remark Provided', max_length=5000),
        ),
    ]
