# Generated by Django 4.2.2 on 2023-06-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0023_assignmentremark_code_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcode',
            name='compilation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentcode',
            name='final_cases_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentcode',
            name='running_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentcode',
            name='test_cases_score',
            field=models.IntegerField(default=0),
        ),
    ]
