# Generated by Django 4.2.2 on 2023-06-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0024_assignmentcode_compilation_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentremark',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='useAuth.assignmentsubmission'),
        ),
    ]
