# Generated by Django 4.2.2 on 2023-07-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0026_assignmentsubmission_deadline_met'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
