# Generated by Django 4.2.2 on 2023-07-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0028_course_accepted_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='request_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
