# Generated by Django 4.2.2 on 2023-07-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0029_coursedetail_request_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentremark',
            name='compilation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignmentremark',
            name='final_cases_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignmentremark',
            name='running_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignmentremark',
            name='test_cases_score',
            field=models.IntegerField(default=0),
        ),
    ]
