# Generated by Django 4.2.2 on 2023-07-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useAuth', '0030_alter_assignmentremark_compilation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentremark',
            name='code_quality',
            field=models.IntegerField(default=0),
        ),
    ]
