# Generated by Django 4.2.2 on 2023-08-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useAuth", "0031_assignmentremark_code_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AssignmentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(default="No Remark Provided", max_length=5000),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useAuth.assignment",
                    ),
                ),
                (
                    "student_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_one",
                        to="useAuth.profile",
                    ),
                ),
                (
                    "student_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_two",
                        to="useAuth.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("assignment", "student_one", "student_two")},
            },
        ),
    ]
