# Generated by Django 4.2.2 on 2023-09-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useAuth", "0032_assignment_is_group_assignmentgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="group",
            field=models.CharField(
                choices=[("TEACHER", "Teacher"), ("STUDENT", "Student"), ("TA", "Ta")],
                default="TEACHER",
                max_length=20,
            ),
        ),
    ]
